# Generated by Django 3.2.7 on 2021-09-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcation',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
