# Generated by Django 3.2.7 on 2021-09-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transcation_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcation',
            options={'ordering': ['-date']},
        ),
    ]
